config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations"}

  get '/' => 'home#index'

  resources :users do
    get 'search', on: :collection
    resources :issues
  end

  resources :comments, only: [:create, :new]

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	has_many :comments

  belongs_to :opener, class_name: "User"
  belongs_to :receiver, class_name: "User"

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_action :authenticate_user!

	def index

    if current_user
      if current_user_visiting_his_issues?
        send_current_user_values_to_index
      else
        send_user_from_url_values_to_public_issues
        render 'public_issues'
      end
    else
      redirect_to '/'
    end

	end


	def create
    opener = User.find_by(plate: params[:issue][:receiver_id])
    @plate = params[:issue][:receiver_id]
    if opener
      @issue = Issue.new(issue_params)
      @issue.receiver_id = opener.id
      @plate_of_issue_opener = User.find_by(id: @issue.opener_id).plate
  		if @issue.save
        IssueMailer.issue_created(@issue, @plate_of_issue_opener).deliver
  			respond_to do |format|
  				format.js do
  					render(
  						partial: 'create_issue',
  						locals: { resource: @issue })
  				end
  			end
  		end
    else
          #render 'user_does_not_exist'
      respond_to do |format|
        format.js do
          render(
            partial: 'user_does_not_exist_msg',
            locals: { resource: @plate })
        end
      end
    end
	end

	def show
    if current_user
      if current_user_visiting_his_issues? and url_issue_is_related_to_current_user?
    		@issue = Issue.find (params[:id])
    		@comments = @issue.comments.order(created_at: :desc)
    		@comment = Comment.new
      else
        @user = User.new
        @related_to_user = false
        render 'this_issue_is_not_related_to_you'
      end
    else
      redirect_to '/'
    end
	end


  private

  def current_user_visiting_his_issues?
    user_from_url = User.find params[:user_id]
    current_user_visiting_his_issues = current_user == user_from_url
  end

  def send_current_user_values_to_index
      @issue = Issue.new
      @user = current_user
      @received_issues = @user.received_issues.order(created_at: :desc)
      @opened_issues = @user.opened_issues.order(created_at: :desc)
  end

  def send_user_from_url_values_to_public_issues
      user_from_url = User.find params[:user_id]
      @issue = Issue.new  
      @user = user_from_url
      @opened_issues = @user.opened_issues.order(created_at: :desc)
  end

  def issue_params
    params.require(:issue).permit(:opener_id, :description)
  end

  def url_issue_is_related_to_current_user?
    issue_url = Issue.find params[:id]
    current_user_related_issues = current_user.opened_issues + current_user.received_issues
    current_user_related_issues.include? issue_url
  end


end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_search_users_by_plate.html.erb
<%= form_tag search_users_path, method: :get, class: 'search_plates' do %>
  <%= search_field_tag :plate_target, params[:plate_target], placeholder: "Search plates", size: 10 %>
  <%= submit_tag "Search", class: "search_plates_button" %>
  <% if flash[:error] %>
   <div> <%= flash[:error] %> </div>
  <% end %>
<% end %>

app/views/issues/index.html.erb
<section class="home_with_user col_11">

	<section class="new_issue_form col_9">
		<h1 class="new_issue_form_title">Create new issue</h1>
		<div class="form col_6">
			<%= form_for [@user, @issue], remote: true, :html => {class: "new_issue"} do |f| %>

				<%= f.label :receiver_id, 'Plate: ' %>
				<br>
				<%= f.text_field :receiver_id, size: 10, placeholder: 'Ex: 1234AAA' %>
				<br>
				<%= f.label :description, 'Description: ' %>
				<br>
				<%= f.text_area :description, class: "textarea", size: "30x5", placeholder: "Park issue description" %>
				<br>
				<%= f.hidden_field :opener_id, value: @user.id %>

				<%= f.submit 'Save', class: "new_issue_button" %>

			<% end %>
		</div>
	</section>

	<div class="issues_lists col_9">

		<section class="my_opened_issues col_4">
			<h1 class="my_opened_issues_title">Opened issues</h1>
			<div class="opened_issues_wrapper">
				<% if @opened_issues.count != 0 %>
					<% @opened_issues.each do |issue| %>
						<article class="media status attribution each_issue">
							<p class="link<%="#{issue.id}"%>"> <%=link_to 'Take me to the issue', user_issue_path(current_user.id, issue.id) %> </p>
						  <div class="bd">
								<p><bold>Issue receiver:</bold> <%= issue.receiver.plate.to_s.upcase.insert(4, ' ')%></p>
								<p><bold>Creation date:</bold> <%= issue.created_at.to_s[0..-5] %></p>
								<p><bold>Issue description:</bold> <%= truncate(issue.description , length: 10)%></p>
							</div>
						</article>
					<% end %>
				<% else %>
					<p class="empty_opened_issues_message"> You have not opened any issue </p>
				<% end %>
			</div>
		</section>

		<section class="my_received_issues col_4">
			<h1>Received issues</h1>
			<div>
				<% if @received_issues.count != 0 %>
					<% @received_issues.each do |issue| %>
						<article class="media status attribution each_issue">
							<p class="link<%="#{issue.id}"%>"> <%=link_to 'Take me to the issue', user_issue_path(current_user.id, issue.id) %> </p>
						  <div class="bd">
								<p><bold>Issue opener:</bold> <%= issue.opener.plate.to_s.upcase.insert(4, ' ')%></p>
								<p><bold>Creation date:</bold> <%= issue.created_at.to_s[0..-5] %></p>
								<p><bold>Issue description:</bold> <%= issue.description %></p>
							</div>
						</article>
					<% end %>
				<% else %>
					<p class="empty_received_issues_message"> You have not received any issue </p>
				<% end %>
			</div>
		</section>

	</div>

</section>

app/views/issues/public_issues.html.erb
  <section class="home_with_user col_11">

    <div class="issues_lists col_9">

      <section class="my_opened_issues col_4">
        <h1 class="my_opened_issues_title">Opened issues</h1>
        <div class="opened_issues_wrapper">
          <% if @opened_issues.count != 0 %>
            <% @opened_issues.each do |issue| %>
              <article class="media status attribution each_issue">
                <p class="link<%="#{issue.id}"%>"> <%=link_to 'Take me to the issue', user_issue_path(current_user.id, issue.id) %> </p>
                <div class="bd">
                  <p><bold>Issue receiver:</bold> <%= issue.receiver.plate.to_s.upcase.insert(4, ' ')%></p>
                  <p><bold>Creation date:</bold> <%= issue.created_at.to_s[0..-5] %></p>
                  <p><bold>Issue description:</bold> <%= truncate(issue.description , length: 10)%></p>
                </div>
              </article>
            <% end %>
          <% else %>
            <p class="empty_opened_issues_message"> <%= @user.plate.to_s.upcase.insert(4, ' ')%> has not opened any issues yet </p>
          <% end %>
        </div>
      </section>

    </div>

  </section>

app/views/issues/show.html.erb
<div class="comments_page_wrapper col_10">

  <div class="issue_and_comments col_6">
    
    <section class="issue_shown col_4">
      <h1 class="issue_shown_title">Issue</h1>
      <div class="issue_shown_wrapper">
        <article class="issue">
          <div class="bd">
        		<p>Issue receiver: <%= @issue.receiver.plate.to_s.upcase.insert(4, ' ')%></p>
        		<p>Creation date: <%= @issue.created_at.to_s[0..-5] %></p>
        		<p>Issue description: <%= @issue.description %></p>
        	</div>
        </article>
      </div>
    </section>

    <section class="comments col_4">
      <h1 class="comments_title">Comments</h1>
      <div class="comments_wrapper">
        <% if @comments.count > 0 %>
          <% @comments.each do |comment| %>
          	<article class="comment each_comment">
              <p><bold>Creation date:</bold> <%= comment.created_at.to_s[0..-5] %></p>
          		<p><bold>Comment´s body:</bold> <%= comment.body %></p>
          	</article>
          <% end %>
        <% else %>
          <p class="no_comments">The issue has not comments yet</p>
        <% end %>
      </div>
    </section>

  </div>

  <section class="new_comment_form col_3">
    <h1 class="new_comment_form_title">Post a comment</h1>
    <div class="form_wrapper">
      <%= form_for [@comment], remote: true, format: :js, :html => {class: "new_comment"} do |f| %>
      		<%= f.label :body, 'Body: ' %>
      		<%= f.text_field :body, placeholder: " Comment body" %>
      		<%= f.hidden_field :issue_id, value: @issue.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>

      		<%= f.submit 'Save' , :id => 'new_comment', class: 'new_comment_button' %>
      <% end %>
    </div>
  </section>

</div>

app/views/issues/this_issue_is_not_related_to_you.html.erb
<p class="not_related_to_you">Sorry, you can´t see this issue because it´s not related to you</p>