config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations"}

  get '/' => 'home#index'

  resources :users do
    get 'search', on: :collection
    resources :issues
  end

  resources :comments, only: [:create, :new]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to user_issues_path(current_user.id) 
    else  
      @user = User.new
      render 'index'
    end
  end

end

app/views/home/_new_user.html.erb
	<%= form_for(resource, :html => {class: "new_user", :id => "new_user"}, as: resource_name, url: registration_path(resource_name)) do |f| %>
	  <%= devise_error_messages! %>

	  <div class="field">
	    <%= f.label :email %><br />
	    <%= f.email_field :email, autofocus: true %>
	  </div>

	  <div class="field">
	    <%= f.label :plate %><br />
	    <%= f.text_field :plate, autofocus: true %>
	  </div>

	  <div class="field">
	    <%= f.label :password %>
	    <% if @validatable %>
	    <em>(<%= @minimum_password_length %> characters minimum)</em>
	    <% end %><br />
	    <%= f.password_field :password, autocomplete: "off" %>
	  </div>

	  <div class="field">
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, autocomplete: "off" %>
	  </div>

	  <div class="actions">
	    <%= f.submit "Sign up", class: "new_user_button" %>
	  </div>
	<% end %>

app/views/home/index.html.erb
<div class="home_container col_7">

  <section class="product_description">
    <h1>Solve your parking issues in some simple steps</h1>
<div>    <ul>
      <li>Sign up</li>
      <li>Create an issue with your parking problem</li>
      <li>Chat with the other driver involved to solve the issue</li>
      <li>Done!</li>
    </ul></div>
  </section>
  <section class="signup">
    <%= render partial: "new_user", locals: {resource: @user} %>
  </section>

</div>