config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations"}

  get '/' => 'home#index'

  resources :users do
    get 'search', on: :collection
    resources :issues
  end

  resources :comments, only: [:create, :new]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

  def after_sign_in_path_for(resource_or_scope)
    "/users/#{current_user.id}/issues"
	end

	def after_sign_out_path_for(resource_or_scope)
	  "/"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def not_empty_user? user
  	user.id.present?
  end

end

app/views/application/_create_comment.js.erb
$('.comments').append(' \
  <article class="comment each_comment"> \
    <p><bold>Creation date:</bold> <%= resource.created_at.to_s[0..-5] %></p> \
		<p><bold>Comment´s body:</bold> <%= resource.body %></p> \
	</article> \
');

$('.no_comments').hide();
$('#comment_body').val('');

app/views/application/_create_issue.js.erb
$('.opened_issues_wrapper').prepend(' \
<article class="media status attribution each_issue"> \
  <p> <%=link_to "Take me to the issue", user_issue_path(current_user.id, resource.id) %> </p> \
  <div class="bd"> \
		<p><bold>Issue receiver:</bold> <%= resource.receiver.plate.to_s.upcase.insert(4, ' ')%></p> \
		<p><bold>Creation date:</bold> <%= resource.created_at.to_s[0..-5] %></p> \
		<p><bold>Issue description:</bold> <%= resource.description %></p> \
	</div> \
</article> \
');

$('.empty_opened_issues_message').hide();

$('#issue_receiver_id').val('');
$('#issue_description').val('');

app/views/application/_new_session.html.erb
<%= form_for(resource, :html => {class: "new_session", :id => "new_session"}, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :plate %>
    <%= f.text_field :plate, size: 10, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="actions">
    
    <div class="button">
      <%= f.submit "Log in", class: 'new_session_button' %>
    </div>

    <% if devise_mapping.rememberable? -%>
      <div class="remember_me">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
    <% end -%>

  </div>

<% end %>

app/views/application/_user_does_not_exist_msg.js.erb
if ($('.plate_doesnt_exist').length === 0) {
  $('#issue_receiver_id').after('<p class="plate_doesnt_exist"> The plate "<%= @plate %>" does not exist </p>');
}

$('.plate_doesnt_exist').delay(1000).fadeOut(2000, function() {
        $(this).remove();
    });