config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations"}

  get '/' => 'home#index'

  resources :users do
    get 'search', on: :collection
    resources :issues
  end

  resources :comments, only: [:create, :new]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
  <title>Platecom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
  <header>
    <% if user_signed_in? %>

    <% if current_user.id != params[:user_id] %>
      <p> <%=link_to 'My Issues', user_issues_path(current_user.id) %> </p>
    <% end %>

      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
        data: { confirm: 'Are you sure?' } %>

<div class="app_name">
  Platecomunicator
</div>

      <div class="plate">
        
        <div>
          <div class="dot left top"></div>
          <div class="dot right top"></div>
        </div>

        
          <p><%= current_user.plate.to_s.upcase.insert(4, ' ')  %></p>
        

        <div>
          <div class="dot left bottom"></div>
          <div class="dot right bottom"></div>
        </div>
        
      </div>
    <% else %>
      <section class="login">
        <%= render partial: "new_session", locals: {resource: @user} %>
      </section>
    <% end %>
  </header>

<div class="container">
  <% if @related_to_user == false %>

  <% else %>
    <% if user_signed_in? %>
      <%= render "search_users_by_plate" %>
    <% end %>
  <% end %>
  <%= yield %>
</div>
  


  <footer>
  </footer>
</body>

</html>